#!/usr/bin/env python3
"""
ChainLink CLI - Deploy and validate the chain-link application in to a 
Kubernetes cluster
"""

from cli.cli_manager import run_cli


if __name__ == "__main__":
    run_cli()
